spring:
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: your_password_here        # Ensure you include the password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: